name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Lint with pre-commit
        uses: pre-commit/action@v3.0.0
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install .
      # - name: Run test
      #   run: ...
